CharApp/Controllers/GeneratorController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net.Mime;
using System.Web;
using System.Web.Mvc;
using CharApp.Models;
using CharApp.Repositorys;
using Microsoft.AspNet.Identity;

namespace CharApp.Controllers
{
    public class GeneratorController : Controller //GeneratorController der tager sig af views der behandler genererede character objekter.
    {
        //Character repository deklareres.
        CharacterRepository CharRepos =  new CharacterRepository();
        
        //Index GET metode.
        [HttpGet]
        public ActionResult Index()
        {
            
            return View();
        }

        //Index POST metode.
        [HttpPost]
        public ActionResult GeneratedIndex()
        {
            //RandomGenerator objekt rand kaldes, og metoden .GenerateChar() der returnerer et nyt Character objekt, kaldes på rand.
            RandomGenerator rand = new RandomGenerator();

            return View(rand.GenerateChar());
        }
        //SaaveGenereatedCharacter GEt metode der tager integeren id ind.
        [HttpGet]
        public ActionResult SaveGeneratedCharacter(int id)
        {
            //character object findes i repositoriet v.h.a id.
            Character character = CharRepos.Find(id);
            return View(character);
        }

        //SaveGeneratedCharacter viewets POST metode der tager integeren id og et billede ind som parametere.
        [Authorize] // Bruger skal være logget ind for at gemme sin nye character.
        [HttpPost]
        public ActionResult SaveGeneratedCharacter(int id, HttpPostedFileBase image)
        {
            //character objekt findes i repository v.h.a id 
            Character character = CharRepos.Find(id);
            
            //Billede gemmes.
            string path = Server == null ? "" : Server.MapPath("~");
            character.SaveImage(image, path, "/UserUploads/CharacterImages/");
            
            //Nuværende brugers id bliver sat i characterns .owner property.
            var user = User.Identity.GetUserId();
            character.owner = user;

            //character gemmes.
            CharRepos.InsertOrUpdate(character);
            CharRepos.Save();

            return RedirectToAction("Index");


        }
        
        //Action metode der tager integeren id ind.
        public ActionResult DiscardGeneratedCharacter(int id)
        {
            //Nyligt generede character objekt slette.
            CharRepos.Delete(id);
            CharRepos.Save();

            return RedirectToAction("Index");
       }

    }
}

CharApp/Views/Generator/GeneratedIndex.cshtml
@using System.Data.Entity.ModelConfiguration.Conventions
@using CharApp.Controllers
@using CharApp.Models
@model CharApp.Models.Character

@{
    ViewBag.Title = "GeneratedIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br/>

<h3>Generated Character</h3>

@*Viewet viser felter med genereret indhold, samt indeholder en knap der ved tryk
  kalder GET SaveGeneratedCharacter metoden i GeneratorControlleren og passer relevante data *@
<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BodyType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BodyType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quirk)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quirk)
        </dd>


    </dl>
</div>
@using (Html.BeginForm("SaveGeneratedCharacter", "Generator", new { id = Model.CharID }, FormMethod.Get))
{ 
    <div class="form-group">
        <div class="row">
            <div class="col-md-offset-2  col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
    <p>
        @Html.ActionLink("Back", "DiscardGeneratedCharacter", new {id = Model.CharID})
    </p>
   
 

CharApp/Views/Generator/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />

<div class="text-center"><h2> Character Generator 3000</h2></div>

@*Knap der ved tryk klader POST metoden *@

@using (Html.BeginForm("GeneratedIndex", "Generator"))
{

    <br/>
    <br />
    <br />
    
    <div class="text-center" >
        <div class ="row"></div><input class="btn btn-success btn-lg" type="submit" value="GENERATE" />
    </div>

    <br />
    <br />
    <br />


}

CharApp/Views/Generator/SaveGeneratedCharacter.cshtml
@model CharApp.Models.Character

@{
    ViewBag.Title = "SaveGeneratedCharacter";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Save your fresh character</h2>

@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Character</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CharID)

        <div class="form-group">
            <div class="row">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8, col-xs-12, col-ms-6, col-lg-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">
                @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8, col-xs-12, col-ms-6, col-lg-10">
                    @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">
                @Html.LabelFor(model => model.BodyType, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8, col-xs-12, col-ms-6, col-lg-10">
                    @Html.EditorFor(model => model.BodyType, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.BodyType, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">
                @Html.LabelFor(model => model.Quirk, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8, col-xs-12, col-ms-6, col-lg-10">
                    @Html.EditorFor(model => model.Quirk, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Quirk, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class=" form-group">
            <div class="row">
                @Html.Label("Character Avatar", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8, col-xs-12, col-ms-6, col-lg-10">
                    <img src=@Model.imagePath alt="Profile image" title="ROAR!" />
                    @Html.HiddenFor(x => x.imagePath)
                    <input type="file" name="image" />
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">
                <div class="col-md-offset-2  col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>

            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Cancel", "DiscardGeneratedCharacter", new { id = Model.CharID })
</div>